-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 21:25:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`book` ;

CREATE TABLE IF NOT EXISTS `mydb`.`book` (
  `bkID` INT NOT NULL,
  `bkSeg` VARCHAR(45) NOT NULL,
  `bkName` VARCHAR(45) NOT NULL,
  `bkAuth` VARCHAR(45) NOT NULL,
  `bkLaun` VARCHAR(45) NOT NULL,
  `bkSal` FLOAT NOT NULL,
  PRIMARY KEY (`bkID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`reader` ;

CREATE TABLE IF NOT EXISTS `mydb`.`reader` (
  `rdID` INT NOT NULL,
  `rdDep` VARCHAR(45) NOT NULL,
  `rdName` VARCHAR(45) NOT NULL,
  `rdSex` VARCHAR(45) NOT NULL,
  `rdTitle` VARCHAR(45) NOT NULL,
  `rdLoc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rdID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lend` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lend` (
  `bkID` INT NOT NULL,
  `rdID` INT NOT NULL,
  `lenDate` DATETIME NOT NULL,
  PRIMARY KEY (`bkID`, `rdID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`book`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (445501, 'TP3/12', 'DBI', 'wangqiang', 'KS',17.90);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (445502, 'TP3/12', 'DBI', 'wangqiang', 'KS',17.90);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (445503, 'TP3/12', 'DBI', 'wangqiang', 'KS',17.90);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (332211, 'TP5/10', 'CSAPP', 'liwei', 'GD',18);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (112266, 'TP3/12', 'FOXBASE', 'zhangsan', 'DZ',23.6);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (665544, 'TS7/21', 'GS', 'liuming', 'GD',20);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (114455, 'TR9/12', 'LA', 'sunye', 'BJ',20.8);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (113388, 'TR7/90', 'EN', 'huling', 'QH',12.5);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (446601, 'TP4/13', 'DBB', 'malingyun', 'RM',22.5);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (446602, 'TP4/13', 'DBB', 'malingyun', 'RM',22.5);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (446603, 'TP4/13', 'DBB', 'malingyun', 'RM',22.5);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (449901, 'TP4/14', 'FOXPRO', 'zhouhong', 'KS',32.7);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (449902, 'TP4/14', 'FOXPRO', 'zhouhong', 'KS',32.7);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (118801, 'TP4/15', 'NET', 'huanglijun', 'GD',21.8);
INSERT INTO `mydb`.`book` (`bkID`, `bkSeg`, `bkName`, `bkAuth`, `bkLaun`, `bkSal`) VALUES (118802, 'TP4/15', 'NET', 'huanglijun', 'GD',21.8);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`reader`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (111, 'in', 'wangweili', 'f', 'pro', '1424');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (112, 'fi', 'lili', 'm', 'vpro', '2316');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (113, 'ec', 'zhangsan', 'm', 'lec', '3105');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (114, 'in', 'zhouhuafa', 'm', 'lec', '1316');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (115, 'in', 'zhaozhengyi', 'm', 'eng', '1224');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (116, 'in', 'liming', 'm', 'vpro', '1318');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (117, 'cs', 'lixiaofeng', 'm', 'asslec', '1214');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (118, 'cs', 'xupengfei', 'm', 'asswork', '1216');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (119, 'cs', 'liudalong', 'm', 'pro', '1318');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (120, 'gt', 'lixue', 'm', 'vpro', '4506');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (121, 'gt', 'lishuang', 'f', 'lec', '4510');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (122, 'gt', 'wangchun', 'f', 'lec', '4512');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (123, 'fi', 'shenxiaoxia', 'f', 'asslec', '2202');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (124, 'fi', 'zhuhai', 'm', 'lec', '2210');
INSERT INTO `mydb`.`reader` (`rdID`, `rdDep`, `rdName`, `rdSex`, `rdTitle`, `rdLoc`) VALUES (125, 'fi', 'mayingming', 'm', 'vpro', '2212');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`lend`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (112, 445501, '1997-3-19');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (125, 332211, '1997-2-12');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (111, 445503, '1997-8-21');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (112, 112266, '1997-3-14');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (114, 665544, '1997-10-21');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (120, 114455, '1997-11-2');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (120, 118801, '1997-10-18');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (119, 446603, '1997-12-12');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (112, 449901, '1997-10-23');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (115, 449902, '1997-8-21');
INSERT INTO `mydb`.`lend` (`bkID`, `rdID`, `lenDate`) VALUES (118, 118801, '1997-9-10');

COMMIT;

