DATA SEGMENT
FILE    DB  '1.txt', 0
BUF     DB  100, ?, 100 DUP(7)
FH      DW  ?

ERR_MSG DB 0DH, 0AH, 'ERROR!','$'
WRT_MSG DB 0DH, 0AH, 'OPEN FILE !INPUT TEXT :', 0AH, '$'
SUC_MSG DB 0DH, 0AH, 'SUCCESS', '$'

DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
RANDOM:
    MOV AH, 0
    INT 1AH
    MOV AX, DX
    MOV BX, 0FH
    DIV BX
    MOV DX, AX


CODE ENDS
END RANDOM