-- MySQL Script generated by MySQL Workbench
-- Tue Oct 29 19:12:28 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Project` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `PID` INT NOT NULL,
  `Pname` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `principal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bank` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bank` (
  `BID` INT NOT NULL,
  `Bname` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Loan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Loan` (
  `PID` INT NOT NULL,
  `BID` INT NOT NULL,
  `money` FLOAT NOT NULL,
  `Bdate` DATETIME NOT NULL,
  `Rdate` DATETIME NULL,
  INDEX `fk_Loan_Bank_idx` (`BID` ASC) ,
  INDEX `fk_Loan_Project1_idx` (`PID` ASC) ,
  CONSTRAINT `fk_Loan_Bank`
    FOREIGN KEY (`BID`)
    REFERENCES `mydb`.`Bank` (`BID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Loan_Project1`
    FOREIGN KEY (`PID`)
    REFERENCES `mydb`.`Project` (`PID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Project`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Project` (`PID`, `Pname`, `city`, `principal`) VALUES (101, 'subway', 'bj', 'liuyan');
INSERT INTO `mydb`.`Project` (`PID`, `Pname`, `city`, `principal`) VALUES (102, 'building', 'jn', 'zhanghu');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Bank`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Bank` (`BID`, `Bname`, `city`) VALUES (201, 'gsyh', 'bj');
INSERT INTO `mydb`.`Bank` (`BID`, `Bname`, `city`) VALUES (202, 'nyyh', 'jn');
INSERT INTO `mydb`.`Bank` (`BID`, `Bname`, `city`) VALUES (203, 'jsyh', 'jn');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Loan`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Loan` (`PID`, `BID`, `money`, `Bdate`, `Rdate`) VALUES (101, 201, 300000, '2005-11-10', NULL);
INSERT INTO `mydb`.`Loan` (`PID`, `BID`, `money`, `Bdate`, `Rdate`) VALUES (101, 202, 3000000, '2005-11-15', '2006-11-28');
INSERT INTO `mydb`.`Loan` (`PID`, `BID`, `money`, `Bdate`, `Rdate`) VALUES (102, 202, 200000, '2006-10-15', null);
INSERT INTO `mydb`.`Loan` (`PID`, `BID`, `money`, `Bdate`, `Rdate`) VALUES (102, 203, 500000, '2005-5-6', null);

COMMIT;

