
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP DATABASE IF EXISTS `SC`;
CREATE DATABASE IF NOT EXISTS `SC`;

-- TABLE STUDENT
DROP TABLE IF EXISTS `SC`.`student`;
CREATE TABLE IF NOT EXISTS `SC`.`student`(
	`S` INT NOT NULL,
    `Sname` VARCHAR(45) NOT NULL,
    `Ssex` ENUM('1', '0') NOT NULL,
    PRIMARY KEY(`S`)
) ENGINE = INNODB;

-- TABLE TEACHER
DROP TABLE IF EXISTS `SC`.`teacher`;
CREATE TABLE IF NOT EXISTS `SC`.`teacher` (
	`T` INT NOT NULL,
    `Tname` VARCHAR(45) NOT NULL,
    PRIMARY KEY(`T`)
) ENGINE = INNODB;

-- TABLE SC
DROP TABLE IF EXISTS `SC`.`sc`;
CREATE TABLE IF NOT EXISTS `SC`.`sc` (
  `C` INT NOT NULL,
  `S` INT NOT NULL,
  `grade` INT NOT NULL
) ENGINE = INNODB;


CREATE ROLE student, teacher;
CREATE USER stu1, stu2, tea1, tea2;

GRANT SELECT ON TABLE `SC`.* TO teacher;
GRANT UPDATE(grade) ON TABLE `SC`.`sc` TO teacher;
GRANT SELECT ON TABLE `SC`.`student` TO student;
GRANT SELECT ON TABLE `SC`.`sc` TO student;

GRANT student TO stu1, stu2;
GRANT teacher TO tea1, tea2;
